server:
  port: 8081

spring:
  application:
    name: INVENTORY-MANAGEMENT-SERVICE

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ims_db
    username: root
    password: SecurePass@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true